apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  
# To verify if the nginx-clusterip service can be accessed inside the cluster, you can follow one of the methods below:
# Option 1: Use a temporary Pod for testing:

# kubectl run curl-pod --rm -i -t --image=busybox:1.28 -- /bin/sh
# Inside the pod, try to access the service by name:

# wget -qO- http://nginx-clusterip

# Option 2: Use an ephemeral pod with more tools (like curl and DNS)

# kubectl run curl --rm -i -t --image=curlimages/curl -- sh
# Then run:
# curl http://nginx-clusterip
