## deployment is in 03-svc-clusterip.yml
## to expose minikube to this svc: minikube service svc-nodeport-nginx --url
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31111 # Node Port
  selector:
    app: nginx
