apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31111 # Node Port
  selector:
    app: nginx

# Gcloud firewall rule to open specific port

# gcloud compute firewall-rules create allow-nodeport-31111 \
#   --direction=INGRESS \
#   --priority=1000 \
#   --network=default \
#   --action=ALLOW \
#   --rules=tcp:31111 \
#   --source-ranges=0.0.0.0/0 \
#   --target-tags=gke-cluster-1-9716ebeb-node

