apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
        - name: nginx
          image: nginx:alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "<html><body><h1>DaemonSet on pod: $(hostname)</h1></body></html>" > /usr/share/nginx/html/index.html;
              nginx -g 'daemon off;'
          ports:
            - containerPort: 80
